// Generated by CoffeeScript 1.7.1
yOSON.AppSchema.modules = {
  'application': {
    controllers: {
      'index': {
        actions: {
          'index': function() {
            return yOSON.AppCore.runModule('datatableCfg');
          },
          'reports': function() {
            return yOSON.AppCore.runModule('datatableRep');
          },
          'login': function() {
            return yOSON.AppCore.runModule('datatableCfg');
          },
          'byDefault': function() {}
        },
        allActions: function() {}
      },
      byDefault: function() {},
      allActions: function() {}
    },
    byDefault: function() {},
    allControllers: function() {}
  },
  byDefault: function() {},
  allModules: function() {}
};
