// Generated by CoffeeScript 1.7.1
yOSON.AppCore.addModule("datatableCfg", (function(Sb) {
  var bindEvents, calenSearch, catchDom, checkMsg, closeOthers, declareTable, dom, dropInfo, format, mainSearch, mainTable, openSearch, searchFun, st;
  st = {
    "datatable": "#mainTable",
    "cuzSearch": "#searchMain",
    "trueSearch": "#mainTable_filter input",
    "picker": ".datepicker",
    "status": "#status",
    "amount": "#amount",
    "openPops": ".menu-bar li a",
    "pops": ".custoPop"
  };
  dom = {};
  mainTable = {};
  catchDom = function() {
    dom.datatable = $(st.datatable);
    dom.cuzSearch = $(st.cuzSearch);
    dom.trueSearch = $(st.trueSearch);
    dom.picker = $(st.picker);
    dom.status = $(st.status);
    dom.amount = $(st.amount);
    dom.openPops = $(st.openPops);
    return dom.pops = $(st.pops);
  };
  declareTable = function() {
    return mainTable = dom.datatable.DataTable({
      "lengthChange": false,
      "pagingType": "simple_numbers",
      "info": false
    });
  };
  mainSearch = function() {
    return dom.cuzSearch.keyup(function() {
      dom.trueSearch = $("#mainTable_filter input");
      dom.trueSearch.val($(this).val());
      return dom.trueSearch.trigger('keyup');
    });
  };
  calenSearch = function() {
    dom.picker.datepicker();
    return dom.picker.on("change", function() {
      var $this;
      $this = $(this);
      return mainTable.search($this.val()).draw();
    });
  };
  searchFun = function() {
    mainSearch();
    calenSearch();
    return openSearch();
  };
  openSearch = function() {
    var cus;
    cus = "";
    return dom.openPops.on("click", function() {
      var $this, custo;
      $this = $(this);
      console.log($this);
      console.log(cus);
      custo = $this.parent().find(".custoPop");
      if (custo.is(":visible")) {
        custo.hide();
      } else {
        dom.pops.hide();
        custo.show();
      }
      return cus = $this;
    });
  };
  closeOthers = function() {
    return $(".shown .glyph-plus.color1").click();
  };
  dropInfo = function() {
    return $("#mainTable tbody").on("click", ".btnDD", function() {
      var $this, data, row, tr;
      $this = $(this);
      tr = $(this).closest("tr");
      row = mainTable.row(tr);
      if (row.child.isShown()) {
        $this.removeClass("color1");
        row.child.hide();
        return tr.removeClass("shown");
      } else {
        closeOthers();
        data = {};
        data.backlog = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim.";
        data.effect = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.";
        data.solution = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium.";
        row.child(format(data), 'childRow').show();
        tr.addClass("shown");
        return $this.addClass("color1");
      }
    });
  };
  format = function(d) {
    return '<table class="innerTable">' + '<tr>' + '<td rowspan=3 class="sonSparate"></td>' + '<td class="titleSubTable">DETALLE DE BACKLOG</td>' + '<td colspan="8" class="sonCtn">' + d.backlog + '</td>' + '</tr>' + '<tr>' + '<td class="titleSubTable">DETALLE DE EFECTO</td>' + '<td colspan="8" class="sonCtn">' + d.effect + '</td>' + '</tr>' + '<tr>' + '<td class="titleSubTable">DETALLE DE SOLUCIÓN</td>' + '<td colspan="8" class="sonCtn">' + d.solution + '</td>' + '</tr>' + '</table>';
  };
  checkMsg = function() {
    $(".ctnCtrls input[type=checkbox]").attr("checked", false);
    return $("#mainTable tbody").on("click", ".checkBtn", function() {
      var $this, flagChk, inpt;
      $this = $(this);
      inpt = $this.parent().find("input");
      if (!inpt.is(":checked")) {
        inpt.click();
        $this.removeClass("glyph-mail");
        $this.addClass("glyph-check");
        return flagChk = true;
      } else {
        inpt.click();
        $this.removeClass("glyph-check");
        $this.addClass("glyph-mail");
        return flagChk = false;
      }
    });
  };
  bindEvents = function() {
    declareTable();
    searchFun();
    dropInfo();
    return checkMsg();
  };
  return {
    init: function(oParams) {
      catchDom();
      return bindEvents();
    }
  };
}), ["plugins/jqDatatable.js", "plugins/jqUI.js"]);

yOSON.AppCore.addModule("datatableRep", (function(Sb) {
  var bindEvents, catchDom, declareTable, dom, mainTable, st;
  st = {
    "datatable": "#tblReport"
  };
  dom = {};
  mainTable = {};
  catchDom = function() {
    return dom.datatable = $(st.datatable);
  };
  declareTable = function() {
    return mainTable = dom.datatable.DataTable({
      "lengthChange": false,
      "paging": false,
      "info": false,
      "aoColumns": [
        {
          bSortable: false
        }
      ]
    });
  };
  bindEvents = function() {
    return declareTable();
  };
  return {
    init: function(oParams) {
      catchDom();
      return bindEvents();
    }
  };
}), ["plugins/jqDatatable.js"]);
